import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Upload, Play, CheckCircle, X, UserCircle as LoaderCircle } from 'lucide-react';
import UploadForm from '../components/UploadForm';
import TranscriptionDisplay from '../components/TranscriptionDisplay';

export type TranscriptionStatus = 'idle' | 'uploading' | 'processing' | 'complete' | 'error';

const HomePage: React.FC = () => {
  const [status, setStatus] = useState<TranscriptionStatus>('idle');
  const [progress, setProgress] = useState(0);
  const [transcript, setTranscript] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  
  const handleUpload = async (file: File) => {
    setStatus('uploading');
    setProgress(0);
    setTranscript(null);
    setError(null);
    
    // Simulate upload progress
    const uploadInterval = setInterval(() => {
      setProgress(prev => {
        if (prev >= 100) {
          clearInterval(uploadInterval);
          return 100;
        }
        return prev + 5;
      });
    }, 100);
    
    try {
      // Simulate API call to Python backend
      setTimeout(() => {
        clearInterval(uploadInterval);
        setProgress(100);
        setStatus('processing');
        
        setTimeout(() => {
          // Mock response - this would come from the Python backend
          setTranscript("This is a sample transcription. In a real application, this text would be generated by the Python ML model processing the uploaded audio file. The transcription would contain the full text content from the audio, properly formatted with timestamps and speaker identification where applicable.");
          setStatus('complete');
        }, 2000);
      }, 2000);
    } catch (err) {
      clearInterval(uploadInterval);
      setStatus('error');
      setError('There was an error processing your file. Please try again.');
    }
  };
  
  return (
    <div className="container mx-auto px-4 py-8">
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-4xl mx-auto"
      >
        <div className="text-center mb-8">
          <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3">
            Transform Speech to Text
          </h1>
          <p className="text-lg text-gray-600">
            Accurate audio transcription powered by advanced AI
          </p>
        </div>
        
        {status === 'idle' && (
          <UploadForm onUpload={handleUpload} />
        )}
        
        {status === 'uploading' && (
          <UploadProgressCard progress={progress} />
        )}
        
        {status === 'processing' && (
          <ProcessingCard />
        )}
        
        {status === 'error' && (
          <ErrorCard message={error} onRetry={() => setStatus('idle')} />
        )}
        
        {status === 'complete' && transcript && (
          <TranscriptionDisplay text={transcript} />
        )}
      </motion.div>
    </div>
  );
};

const UploadProgressCard: React.FC<{ progress: number }> = ({ progress }) => (
  <motion.div 
    initial={{ opacity: 0, scale: 0.95 }}
    animate={{ opacity: 1, scale: 1 }}
    className="bg-white rounded-xl shadow-md overflow-hidden"
  >
    <div className="p-6">
      <div className="flex items-center justify-center mb-4">
        <Upload className="h-12 w-12 text-blue-500" />
      </div>
      <h3 className="text-xl font-semibold text-center mb-4">Uploading your audio</h3>
      <div className="w-full bg-gray-200 rounded-full h-2.5">
        <div 
          className="bg-blue-500 h-2.5 rounded-full transition-all duration-300 ease-out"
          style={{ width: `${progress}%` }}
        ></div>
      </div>
      <p className="text-center text-gray-500 mt-3">{progress}% complete</p>
    </div>
  </motion.div>
);

const ProcessingCard: React.FC = () => (
  <motion.div 
    initial={{ opacity: 0, scale: 0.95 }}
    animate={{ opacity: 1, scale: 1 }}
    className="bg-white rounded-xl shadow-md overflow-hidden"
  >
    <div className="p-6">
      <div className="flex items-center justify-center mb-4">
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ repeat: Infinity, duration: 2, ease: "linear" }}
        >
          <LoaderCircle className="h-12 w-12 text-blue-500" />
        </motion.div>
      </div>
      <h3 className="text-xl font-semibold text-center mb-4">Processing your audio</h3>
      <p className="text-center text-gray-500">
        Our AI is analyzing your audio and generating a transcript. This may take a few moments.
      </p>
    </div>
  </motion.div>
);

const ErrorCard: React.FC<{ message: string | null, onRetry: () => void }> = ({ message, onRetry }) => (
  <motion.div 
    initial={{ opacity: 0, scale: 0.95 }}
    animate={{ opacity: 1, scale: 1 }}
    className="bg-white rounded-xl shadow-md overflow-hidden border border-red-200"
  >
    <div className="p-6">
      <div className="flex items-center justify-center mb-4">
        <X className="h-12 w-12 text-red-500" />
      </div>
      <h3 className="text-xl font-semibold text-center mb-4">Transcription failed</h3>
      <p className="text-center text-gray-700 mb-4">
        {message || 'There was an error processing your file. Please try again.'}
      </p>
      <div className="flex justify-center">
        <button 
          onClick={onRetry}
          className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 transition-colors"
        >
          Try again
        </button>
      </div>
    </div>
  </motion.div>
);

export default HomePage;